### ISSUE TITLE
Hiding job gauges through HUD Layout breaks Gauge-O-Matic trackers

### ISSUE THREAD

**Issue by Enriath** [ItsBexy/GaugeOMatic#10]
Version: v0.7.0.0

With the latest update to support Dawntrail, I noticed that the option to hide the job gauges was made vanilla, and thus (mostly) removed from the plugin. While I love this change, Gauge-O-Matic doesn't really handle it well. Trackers pinned to the job gauge will be hidden along with it, and even trackers pinned to the Parameter Bar will stop updating when the job gauge is hidden.

**Comment by ItsBexy** [comment]
The hide gauge tweaks have been restored, and the next update will have some refactoring that will hopefully get the plugin to handle hidden gauges better.
