### ISSUE TITLE
BLM High Thunder / High Thunder II not tracking properly

### ISSUE THREAD

**Issue by Kokkosoulis** [ItsBexy/GaugeOMatic#11]
![image](https://github.com/user-attachments/assets/48833a39-22eb-439f-804c-dd5a0e9d805c)

High Thunder II isn't an option in the tracker dropdown, but isn't tracked by the HT tracker either

**Comment by ItsBexy** [comment]
Thanks for the heads-up. I believe this will be fixed in next update (I spotted and corrected at least one error in my data), but I haven't levelled BLM past 90 so I don't have a direct way to test High Thunder. Feel free to let me know if the next plugin version doesn't do the trick.
