### ISSUE TITLE
BRD buff durations not updated following 7.0 changes

### ISSUE THREAD

**Issue by Trobador** [ItsBexy/GaugeOMatic#12]
Hi, thank you for your work on Gauge-O-Matic!

Radiant Finale and Battle Voice's durations were buffed from 15s to 20s in 7.0, but as I write this, Gauge-O-Matic still has their maximum at 15s. This leads to bar indicators not draining during the first five seconds of these buffs.

To recreate, simply add a widget tracking either buff with a bar or timer tracker and turn on its test mode. Timers will show 15 seconds.

**Comment by ItsBexy** [comment]
Fixed in next update!
