### ISSUE TITLE
loving the plugin so far 

### ISSUE THREAD

**Issue by Nicolas-GE** [ItsBexy/GaugeOMatic#6]
i just had a simple question, i've never seen thoes inkslash and mahjong gauges, where did they come from?

**Comment by ItsBexy** [comment]
Those are original designs I created from miscellaneous other textures in the game. Mahjong Ribbon is of course made from Mahjong UI textures. Inkslash is made from a combination of the Mob Hunt Board UI and the RDM gauge.
