### ISSUE TITLE
Spineshatter Dive tracker changing early

### ISSUE THREAD

**Issue by lael-i** [ItsBexy/GaugeOMatic#8]
Sorry to spam you with issues but I thought it would be easier to keep organised. My availability gem for Spineshatter Dive seems to be refreshing at 30 seconds, rather than the full cooldown of 60.
![image](https://github.com/ItsBexy/GaugeOMatic/assets/68711143/fca648bc-8a18-4945-96e4-c691ee49fb70)
![image](https://github.com/ItsBexy/GaugeOMatic/assets/68711143/c694318e-a5b1-4a07-99be-33b020302257)
I would assume this to be related to the fact that the ability gains multiple charges at level 84, causing it to misbehave when tracked below that level.

**Comment by ItsBexy** [comment]
Thanks for the heads-up, and apologies for not getting around to fixing it back when Spineshatter Dive existed, but at least I suppose the problem has solved itself?
